apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: api-health-analysis
spec:
  metrics:
  - name: error-rate-check
    interval: 20s # Cứ 20s truy vấn Prometheus 1 lần
    # Phải thành công liên tiếp, nếu thất bại 2 lần -> Rollback
    failureLimit: 2 
    # Điều kiện thành công: Tỷ lệ lỗi HTTP 5xx phải < 2% (0.02)
    successCondition: result[0] <= 0.02
    provider:
      prometheus:
        # IP của máy Worker đang chạy Prometheus Docker-compose
        address: http://192.168.122.22:9090
        query: |
          (sum(increase(http_request_duration_seconds_count{app="api-gateway", status_code=~"5.*"}[1m])) or vector(0))
          /
          (sum(increase(http_request_duration_seconds_count{app="api-gateway"}[1m])) > 0 or vector(1))