# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: api-gateway
#   labels:
#     app: api-gateway
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: api-gateway
#   template:
#     metadata:
#       labels:
#         app: api-gateway
#     spec:
#       containers:
#         - name: api-gateway
#           image: "{{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag }}"
#           imagePullPolicy: {{ .Values.apiGateway.image.pullPolicy }}
#           ports:
#             - containerPort: {{ .Values.apiGateway.service.port }}