apiVersion: v1
kind: Service
metadata:
  name: product-service-service
  labels:
    app: product-service
spec:
  type: NodePort
  selector:
    app: product-service
  ports:
    - port: {{ .Values.productService.service.port }}
      targetPort: {{ .Values.productService.service.port }}
      nodePort: {{ .Values.productService.service.nodePort }}