apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  labels:
    app: user-service
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - port: {{ .Values.userService.service.port }}
      targetPort: {{ .Values.userService.service.port }}
      nodePort: {{ .Values.userService.service.nodePort }}